name: gingold
favicon: null
layout_spectrum: 0.77737
typography_spectrum: 0.72074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#676767'
    - '#00afd1'
    - '#94d8e9'
    - '#45bfd7'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
