name: gingold
favicon: null
layout_spectrum: 0.9647400449030101
typography_spectrum: 0.9062397060915828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8964085322804749
  lightness: 0.31754171079955995
  saturation: 0.5743236979469657
  rhythmicContrast: 0.46069579292088747
purpose: []
