name: gingold
favicon: null
layout_spectrum: 0.52861
typography_spectrum: 0.74562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#676767'
    - '#00afd1'
    - '#94d8e9'
    - '#45bfd7'
  brandStrength: 0.25
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
